FROG_SPEED = 50

WATER_TOP = 150
WATER_BOTTOM = 400

SCREEN_WIDTH = 750
SCREEN_HEIGHT = 900
SCREEN_LANE_PADDING = 6

FROG_LIVES = 5
FROG_START_X = SCREEN_WIDTH // 2 - 20
FROG_START_Y = SCREEN_HEIGHT - 100 + SCREEN_LANE_PADDING